import { LEVEL_IDS, LEVELS } from "../levels";

export function mountAppShell(app: HTMLElement, dev = import.meta.env.DEV) {
  const devButton = (id: string) =>
    dev ? `<button id="${id}" type="button">DEV MENU</button>` : "";
  app.innerHTML = `
    <div class="menu" id="main-menu"><h1 class="menu__title">EXOWING</h1><div class="menu__actions"><button id="start-button" type="button">START</button><button id="start-settings-button" type="button">SETTINGS</button>${devButton("start-dev-settings-button")}</div></div>
    <div class="menu" id="pause-menu" hidden><h1 class="menu__title">PAUSED</h1><div class="menu__actions"><button id="continue-button" type="button">CONTINUE</button><button id="settings-button" type="button">SETTINGS</button><button id="controls-button" type="button">CONTROLS</button><button id="main-menu-button" type="button">MAIN MENU</button>${devButton("dev-settings-button")}</div></div>
    <div class="menu" id="settings-menu" hidden><button class="menu__back" id="settings-back" type="button">BACK</button><div class="settings"><h1>SETTINGS</h1><h2 class="settings__section-title">GRAPHICS</h2><div class="setting-row"><div class="setting-row__label"><span>RESOLUTION</span><small id="render-resolution"></small></div><select id="render-scale" aria-label="Graphics quality"><option value="0.5">LOW</option><option value="0.75">MEDIUM</option><option value="1">HIGH</option></select></div><label class="setting-row setting-toggle"><span>ANTI-ALIASING</span><input id="anti-aliasing" type="checkbox"></label><label class="setting-row setting-toggle"><span>TARGETING RETICLE</span><input id="targeting-reticle" type="checkbox"></label><h2 class="settings__section-title">AUDIO</h2><label class="setting-row setting-volume"><span>VOLUME</span><span class="setting-volume__control"><input id="master-volume" type="range" min="0" max="1" step="0.01" aria-label="Master volume"><output id="master-volume-value" for="master-volume">82%</output></span></label></div></div>
    <div class="menu" id="controls-menu" hidden><button class="menu__back" id="controls-back" type="button">BACK</button><div class="controls"><h1>CONTROLS</h1><dl><div><dt>MOVE</dt><dd>W A S D</dd></div><div><dt>BARREL ROLL / DODGE</dt><dd>Q / E</dd></div><div><dt>FIRE</dt><dd>SPACE</dd></div><div><dt>FASTER</dt><dd>SHIFT</dd></div><div><dt>BRAKE</dt><dd>ALT</dd></div><div><dt>PAUSE</dt><dd>ESC</dd></div></dl></div></div>
    ${dev ? `<div class="menu" id="dev-menu" hidden><button class="menu__back" id="dev-menu-back" type="button">BACK</button><div class="dev-menu"><h1>DEV MENU</h1><div class="menu__actions"><button id="open-dev-settings" type="button">DEV SETTINGS</button><button id="open-level-switcher" type="button">SWITCH LEVEL</button><button id="open-asset-scaling" type="button">ASSET SCALING</button></div></div></div><div class="menu" id="dev-settings-menu" hidden><button class="menu__back" id="dev-settings-back" type="button">BACK</button><div class="dev-settings"><h1>DEV SETTINGS</h1><label class="dev-setting">INVULNERABLE <input data-dev-setting="invulnerable" type="checkbox"></label><label class="dev-setting">SHOW FPS <input data-dev-setting="showFps" type="checkbox"></label><label class="dev-setting">SHOW MOVEMENT FRAME <input data-dev-setting="showMovementFrame" type="checkbox"></label><label class="dev-setting">SHOW SPLINE <input data-dev-setting="showSpline" type="checkbox"></label></div></div><div class="menu" id="dev-level-menu" hidden><button class="menu__back" id="dev-level-back" type="button">BACK</button><div class="dev-level-switcher"><h1>SWITCH LEVEL</h1><div class="dev-level-list" id="dev-level-list">${LEVEL_IDS.map((id) => `<button type="button" data-dev-level="${id}">${id} · ${LEVELS[id].name.toUpperCase()}</button>`).join("")}</div></div></div><div class="menu asset-scaling-menu" id="asset-scaling-menu" hidden><button class="menu__back" id="asset-scaling-back" type="button">BACK</button><div class="asset-scaling"><h1>ASSET SCALING</h1><p class="asset-scaling__help">COMPARE UP TO THREE ASSETS · DRAG TO ORBIT · SCROLL TO ZOOM</p><div class="asset-scaling__preview" id="asset-scaling-preview"><p id="asset-scaling-status">LOADING ASSETS…</p></div><div class="asset-scaling__controls" id="asset-scaling-controls"></div><button id="copy-asset-scales" type="button">COPY SCALES</button><p class="asset-scaling__feedback" id="asset-scaling-feedback" aria-live="polite"></p></div></div>` : ""}
    <div class="damage-vignette" id="damage-vignette" aria-hidden="true"></div><div class="level-transition" id="level-transition" aria-live="polite"><span id="level-transition-label">LEVEL 1</span></div>
    <div class="loading-screen" id="loading-screen" hidden aria-live="polite" aria-busy="true"><div class="loading-screen__content"><p class="loading-screen__eyebrow" id="loading-eyebrow">PREPARING SORTIE</p><h1 id="loading-title">LEVEL 1</h1><div class="loading-screen__track"><div class="loading-screen__fill" id="loading-fill"></div></div><p class="loading-screen__status" id="loading-status">Loading…</p><button id="loading-retry" type="button" hidden>RETRY</button></div></div>
    <div class="menu" id="game-over-menu" hidden><h1 class="menu__title">GAME OVER</h1><div class="menu__actions"><button id="retry-button" type="button">RETRY</button><button id="game-over-main-menu-button" type="button">MAIN MENU</button></div></div>
    <div class="hud" id="hud" hidden><div class="hud__shield"><div class="hud__eyebrow"><span>SHIELD</span><span id="shield">100%</span></div><div class="hud__shield-track" role="meter" aria-label="Shield" aria-valuemin="0" aria-valuemax="5" aria-valuenow="5"><div class="hud__shield-fill" id="shield-fill"></div></div></div><div class="hud__score"><span class="hud__score-label">SCORE</span><span class="hud__score-value" id="score">0000</span></div><div class="hud__boss" id="boss-health" hidden><div class="hud__eyebrow"><span>GUARDIAN: RIFTMAW</span><span id="boss-health-value">100%</span></div><div class="hud__boss-track"><div class="hud__boss-fill" id="boss-health-fill"></div></div></div><div class="hud__fps" id="fps" hidden>FPS 0</div></div>`;
}

export function requiredElement<T extends Element>(
  selector: string,
  root: ParentNode = document,
): T {
  const element = root.querySelector<T>(selector);
  if (!element) throw new Error(`Missing element: ${selector}`);
  return element;
}
